# Generated by Django 4.2.2 on 2023-07-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_email_alter_clients_name'),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject of the e-mail')),
                ('body', models.TextField(verbose_name='Body of the e-mail')),
            ],
            options={
                'verbose_name': 'mail',
                'verbose_name_plural': 'mails',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_date', models.DateTimeField(auto_now=True, verbose_name='Date of the last attempt')),
                ('attempt_status', models.CharField(choices=[('S', 'success'), ('f', 'failure')], max_length=10, verbose_name='Status of the last attempt')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response of the server')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'ordering': ('-attempt_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='mailings',
            options={'verbose_name': 'mailing', 'verbose_name_plural': 'mailings'},
        ),
        migrations.RemoveField(
            model_name='mailings',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='mailings',
            name='time',
        ),
        migrations.AddField(
            model_name='mailings',
            name='clients',
            field=models.ManyToManyField(to='clients.groups', verbose_name='Group of clients'),
        ),
        migrations.AddField(
            model_name='mailings',
            name='status',
            field=models.CharField(choices=[('C', 'created'), ('R', 'running'), ('CM', 'completed')], default='created', max_length=10, verbose_name='Status of sending'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='frequency',
            field=models.CharField(choices=[('D', 'daily'), ('W', 'weekly'), ('M', 'monthly')], max_length=10, verbose_name='Frequency of sending'),
        ),
        migrations.AddField(
            model_name='mailings',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailings.mail', verbose_name='Text of mailing'),
        ),
    ]
