# Generated by Django 4.2.2 on 2023-07-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mail_mailinglog_alter_mailings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time of sending'),
        ),
    ]
