# Generated by Django 4.2.2 on 2023-07-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailings_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'ordering': ('-time',), 'verbose_name': 'mailing', 'verbose_name_plural': 'mailings'},
        ),
    ]
