# Generated by Django 4.2.2 on 2023-07-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailings.mailings', verbose_name='Mailing'),
        ),
    ]
