# Generated by Django 4.2.2 on 2023-07-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_mailinglog_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('running', 'running'), ('completed', 'completed')], default='created', max_length=10, verbose_name='Status of sending'),
        ),
    ]
