# Generated by Django 4.2.2 on 2023-07-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_email_alter_clients_name'),
        ('mailings', '0006_alter_mailings_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailings',
            name='clients',
        ),
        migrations.AddField(
            model_name='mailings',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.groups', verbose_name='Group of clients'),
        ),
    ]
