# Generated by Django 4.2.2 on 2023-07-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_remove_mailings_clients_mailings_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='attempt_status',
            field=models.CharField(choices=[('success', 'success'), ('failure', 'failure')], max_length=10, verbose_name='Status of the last attempt'),
        ),
    ]
