# Generated by Django 4.2.2 on 2023-07-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_email_alter_clients_name'),
        ('mailings', '0009_mailings_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.groups', verbose_name='Group of clients'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.mail', verbose_name='Text of mailing'),
        ),
    ]
