# Generated by Django 4.2.2 on 2023-07-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0012_mail_owner_mailinglog_owner_mailings_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='owner',
        ),
    ]
