# Generated by Django 4.2.2 on 2023-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=250, verbose_name='Post Title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Preview')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
