# Generated by Django 4.2.2 on 2023-06-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_client_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['-pk'], 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
    ]
