# Generated by Django 4.2.2 on 2023-06-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
    ]
